### PR TITLE
Modular improvements

### PR DESCRIPTION
**Pull request by adam-vessey**
Make FOXML date properties be indexed as dates, prevent some garbage text, and rewrite the "slurp MODS" to use templates instead of for-eaches.

I could push the other Solr config files as well... I think it's a good idea, 'cause then you can just symlink to the "conf" directory wherever this repo gets cloned.

Similarly, the basic GSearch XSLTs (browseIndexToResultPage.xslt, copyXml.xslt, gfindObjectsToResultPage.xslt and updateIndexToResultPage.xslt) and associated files (index.properties and indexInfo.xml) could be thrown here as well, so the entire repo could just be cloned as $CATALINA_HOME/webapps/fedoragsearch/WEB-INF/classes/whatever-config/index/gsearch_solr, to have the majority of a working GSearch configuration.

### CODE REVIEW

**Comment by jmacwilliams** [comment]
can we change the name of that xslt to not include "slurp" it sounds so ....

**Comment by DannyJoris** [comment]
+1

**Comment by adam-vessey** [comment]
Change it to what, though? If someone makes a good suggestion, I'll change it. :+1:

**Comment by adam-vessey** [comment]
... "Simple, Lightweight and Uniform Rewriting for our Purposes"?...  SLURP. :P

**Comment by jonathangreen** [comment]
just mods_to_solr?

**Comment by adam-vessey** [comment]
There already is a "mods_to_solr.xslt"...  It is not used by default though...  Perhaps we could just replace it, and if somebody needs to reference it, they can always go back into the history?

**Comment by jonathangreen** [comment]
makes sense to me. does slurp contain all the features of mods to solr?

**Comment by adam-vessey** [comment]
Other than differing field names, I think that the only "big" difference is the formatting of both personal names (generating fields combining first and last names, both "last, first" and "first last") and titles ("nonSort title").  In "slurping", these would (currently) have to be built by hand...  Could slap in a couple templates to handle titles and names into the slurping?

**Comment by jonathangreen** [comment]
i think that would work. also why is this on a branch? should it get merged into modular?

**Comment by adam-vessey** [comment]
...  This is a pull request, yeah?  I was figuring to have all the changes in in one go. Also, to generate some amount of discussion? :P

**Comment by jonathangreen** [comment]
never mind. i'm dumb. i thought this was a pull request into modular-improvements, but its not.

**Comment by DannyJoris** [comment]
Would extract_all_MODS_to_solr.xslt work?

**Comment by jonathangreen** [comment]
should we rename and merge this before it gets forgotten.

**Pull request merged**
