### PR TITLE
Two suggestions related to large (full-text/ocr) fields and search highlighting.

### PR DESCRIPTION
**Pull request by zacho**
Fuller description in the individual commits.

### CODE REVIEW

**Comment by jmacwilliams** [comment]
Why did you use maxFieldLength=2^30-1 instead of 2^31-1?

**Comment by willtp87** [comment]
I think why this is being set so large should be mentioned in a comment in the file.

**Comment by zacho** [comment]
I don't have a good answer to that (Jason), maybe I thought I would differentiate it from the value above while still for all intents and purposes being infinite.  Others in the wild have set both to 2^31-1.

**Comment by zacho** [comment]
Also, I erroneously stated that maxFieldLength measured in chars, it's actually measured in words/terms.  Still, it has proven too small for pittsburgh and others in the wild.

**Pull request merged**
